apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-api
  template:
    metadata:
      labels:
        app: quote-api
    spec:
      containers:
        - name: quote-api
          image: quoteacrregistry.azurecr.io/quote-api:v1
          ports:
            - containerPort: 5000
